name: Deploy GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  ubuntu-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Try Checkout Github Pages Branch
        continue-on-error: true
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
      - name: Checkout Documentation Branch
        uses: actions/checkout@v2
        with:
          ref: "dev"
          path: "documentation"
      - name: Build Document
        run: |
          cd documentation
          yarn
          yarn run docs:build
          cd ..
          mv documentation/docs/.vuepress/dist dist
          rm -r documentation
      - name: Try Delete Old Version
        continue-on-error: true
        run: |
          rm -r docs
      - name: Rename
        run: |
          mv dist docs
      - name: Push
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.KEY }}
          push-branch: "gh-pages"
          commit-message: "Auto Generate & Deploy"
          force-add: "true"
          files: ./*
          name: Miswanting
          email: ihex@foxmail.com
